title: Impeachment Chronicles
author:
  name: Greg Raven
  email: greg@impeachment.network
description: Attacks on our president and our republic.
url: "https://www.impeachment.network"

# Build settings
theme: minima
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-archives:
  enabled:
    - tags
  layouts:
    tags: tag-archive
  permalinks:
    tags: "/tag/:name/"

# Theme-specific settings

minima:
  skin: auto

# If you want to link only specific pages in your header, uncomment this
# and add the path to the pages in order as they should show up.

header_pages:
  - accomplishments.html
  - timeline.html
  - search.html

# Set to `true` to show excerpts on the homepage.

show_excerpts: true

paginate: 20
